name: Lint Python code
on:
  pull_request:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6

      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Install the dependencies
        run: uv sync

      - name: Run Pylint
        run: uv run -m pylint uc_intg_stormaudio

      - name: Run flake8
        run: uv run -m flake8 uc_intg_stormaudio --count --show-source --statistics

      - name: Check import sorting
        run: uv run -m isort uc_intg_stormaudio/. --check --verbose

      - name: Check code format
        run: uv format --check
